Repository kolyasalubov/ProjectShop, pull requests merged in 2021-10, with the labels that each got.

#140 Small changes, bug fix, and pep8 improve
  ProjectShop/UserApp/backends.py
  ProjectShop/UserApp/forms.py
  ProjectShop/UserApp/templates/UserApp/password_reset_complete.html
  ProjectShop/UserApp/templates/UserApp/profile.html
  ProjectShop/UserApp/urls.py
Labels: Hotfix

#149 Feature x148 create makefile
  ProjectShop/Makefile
Labels: enhancement

#138 Feature#132 order items serializer/ http methods for order
  ProjectShop/ProductApp/migrations/0001_initial.py
  ProjectShop/ProductApp/migrations/0002_initial.py
  ProjectShop/ProductApp/migrations/0003_auto_20210927_1542.py
  ProjectShop/ProjectShop/router.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/UserApp/urls.py
  ProjectShop/order/admin.py
  ProjectShop/order/migrations/0001_initial.py
  ProjectShop/order/models.py
  ProjectShop/order/serializers.py
  ProjectShop/order/urls.py
  ProjectShop/order/views.py
  TelegramBot/dispatcher.py
  TelegramBot/main.py
Labels: DataBase-OrderModel, telegram-bot, REST API

#152 Updated admin for order and fixed bugs
  ProjectShop/order/admin.py
  ProjectShop/order/export.py
Labels: Hotfix

#131 Feature#121 implement products interface via rest
  ProjectShop/ProductApp/models.py
  ProjectShop/ProductApp/serializers.py
  ProjectShop/ProductApp/urls.py
  ProjectShop/ProductApp/views.py
  ProjectShop/ProjectShop/router.py
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/order/serializers.py
Labels: ProductModel, REST API

#135 Feature #71 implement_user_interface_via_REST
  ProjectShop/ProjectShop/router.py
  ProjectShop/UserApp/serializers.py
  ProjectShop/UserApp/urls.py
  ProjectShop/UserApp/views.py
Labels: REST API

#139 Feature #74 implemented shippingAddress interface via REST
  ProjectShop/ProjectShop/router.py
  ProjectShop/Shipping/serializers.py
  ProjectShop/Shipping/urls.py
  ProjectShop/Shipping/views.py
Labels: REST API

#164 hotfix_6_Fix_update_method_for_User
  ProjectShop/UserApp/serializers.py
  ProjectShop/UserApp/views.py
Labels: bug, DataBase-UserModel, Hotfix

#175 Feature#172 add black formatter and flake8 linter
  .pre-commit-config.yaml
  ProjectShop/Makefile
  ProjectShop/ProductApp/admin.py
  ProjectShop/ProductApp/apps.py
  ProjectShop/ProductApp/migrations/0003_auto_20210927_1542.py
  ProjectShop/ProductApp/models.py
  ProjectShop/ProductApp/serializers.py
  ProjectShop/ProductApp/signals.py
  ProjectShop/ProductApp/tests.py
  ProjectShop/ProductApp/utils.py
  ProjectShop/ProductApp/views.py
  ProjectShop/ProjectShop/asgi.py
  ProjectShop/ProjectShop/custom_filters.py
  ProjectShop/ProjectShop/router.py
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/ProjectShop/wsgi.py
  ProjectShop/Shipping/admin.py
  ProjectShop/Shipping/apps.py
  ProjectShop/Shipping/models.py
  ProjectShop/Shipping/serializers.py
  ProjectShop/Shipping/tests.py
  ProjectShop/Shipping/views.py
  ProjectShop/UserApp/admin.py
  ProjectShop/UserApp/apps.py
  ProjectShop/UserApp/backends.py
  ProjectShop/UserApp/forms.py
  ProjectShop/UserApp/managers.py
  ProjectShop/UserApp/models.py
  ProjectShop/UserApp/permissions.py
  ProjectShop/UserApp/serializers.py
  ProjectShop/UserApp/tests/custom_providers.py
  ProjectShop/UserApp/tests/factories.py
  ProjectShop/UserApp/tests/test_forms.py
  ProjectShop/UserApp/urls.py
  ProjectShop/UserApp/views.py
  ProjectShop/WishList/admin.py
  ProjectShop/WishList/apps.py
  ProjectShop/WishList/models.py
  ProjectShop/WishList/tests.py
  ProjectShop/WishList/views.py
  ProjectShop/manage.py
  ProjectShop/media/default_profile_pictures/default_pic.svg
  ProjectShop/order/admin.py
  ProjectShop/order/apps.py
  ProjectShop/order/export.py
  ProjectShop/order/models.py
  ProjectShop/order/serializers.py
  ProjectShop/order/tests.py
  ProjectShop/order/urls.py
  ProjectShop/order/views.py
  ProjectShop/requirements.txt
  TelegramBot/TOKEN.py
  TelegramBot/client/client.py
  TelegramBot/client/models.py
  TelegramBot/dispatcher.py
  TelegramBot/handlers/user_menu.py
  TelegramBot/main.py
  tox.ini
Labels: documentation, Design, #Epic story

#179 Feature x178 Implement Categories and Home Page Functionality
  ProjectShop/ProductApp/templates/ProductApp/categories.html
  ProjectShop/ProductApp/templates/ProductApp/homepage.html
  ProjectShop/ProductApp/urls.py
  ProjectShop/ProductApp/views.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/UserApp/templates/UserApp/_base.html
  ProjectShop/UserApp/templates/UserApp/home.html
  ProjectShop/UserApp/templates/UserApp/profile.html
  ProjectShop/UserApp/views.py
Labels: Backend, Homepage
