Repository kolyasalubov/ProjectShop, pull requests merged in 2021-09, with the labels that each got.

#5 Created user class based on AbstractBaseUser
  ProjectShop/ProjectShop/settings.py
  ProjectShop/UserApp/__init__.py
  ProjectShop/UserApp/admin.py
  ProjectShop/UserApp/apps.py
  ProjectShop/UserApp/managers.py
  ProjectShop/UserApp/migrations/0001_initial.py
  ProjectShop/UserApp/migrations/0002_auto_20210831_2058.py
  ProjectShop/UserApp/migrations/0003_alter_user_options.py
  ProjectShop/UserApp/migrations/__init__.py
  ProjectShop/UserApp/models.py
  ProjectShop/UserApp/tests.py
  ProjectShop/UserApp/views.py
  ProjectShop/requirements.txt
Labels: UserModel

#24 Feature#13 create permissions for users
  ProjectShop/UserApp/admin.py
  ProjectShop/UserApp/managers.py
  ProjectShop/UserApp/migrations/0004_user_is_active.py
  ProjectShop/UserApp/models.py
Labels: UserModel

#27 Feature#3 UML UseCase diagram implementation
  Docs/UMLUseCaseDiagram/AccountManagementSystem.png
  Docs/UMLUseCaseDiagram/DataManagementSystem.png
  Docs/UMLUseCaseDiagram/InStoreManagementSystem.png
Labels: documentation

#18 User forms
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/UserApp/backends.py
  ProjectShop/UserApp/forms.py
  ProjectShop/UserApp/templates/UserApp/login.html
  ProjectShop/UserApp/templates/UserApp/register.html
  ProjectShop/UserApp/views.py
Labels: User-Authentication

#25 Feature x23 user flow implementation
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/UserApp/backends.py
  ProjectShop/UserApp/forms.py
  ProjectShop/UserApp/templates/UserApp/_base.html
  ProjectShop/UserApp/templates/UserApp/home.html
  ProjectShop/UserApp/templates/UserApp/login.html
  ProjectShop/UserApp/templates/UserApp/logout.html
  ProjectShop/UserApp/templates/UserApp/register.html
  ProjectShop/UserApp/templates/flatpages/default.html
  ProjectShop/UserApp/urls.py
  ProjectShop/UserApp/views.py
  ProjectShop/requirements.txt
Labels: User-Authentication

#29 Model#11 order model
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/order/admin.py
  ProjectShop/order/migrations/0001_initial.py
  ProjectShop/order/migrations/0002_order_payment_status.py
  ProjectShop/order/models.py
  ProjectShop/order/router.py
  ProjectShop/order/serializers.py
  ProjectShop/order/urls.py
  ProjectShop/order/views.py
Labels: question, DataBase-OrderModel

#46 Feature#10 create order items model
  ProjectShop/OrderItems/__init__.py
  ProjectShop/OrderItems/admin.py
  ProjectShop/OrderItems/apps.py
  ProjectShop/OrderItems/migrations/__init__.py
  ProjectShop/OrderItems/models.py
  ProjectShop/OrderItems/tests.py
  ProjectShop/OrderItems/views.py
  ProjectShop/ProjectShop/settings.py
Labels: DataBase-OrderModel

#59 Create WishList model.
  ProjectShop/ProjectShop/settings.py
  ProjectShop/WishList/__init__.py
  ProjectShop/WishList/admin.py
  ProjectShop/WishList/apps.py
  ProjectShop/WishList/migrations/__init__.py
  ProjectShop/WishList/models.py
  ProjectShop/WishList/tests.py
  ProjectShop/WishList/views.py
Labels: Database - WishListModel

#94 Feature#79 create access token for rest api
  ProjectShop/OrderItems/migrations/0001_initial.py
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/UserApp/admin.py
  ProjectShop/UserApp/migrations/0001_initial.py
  ProjectShop/UserApp/migrations/0002_auto_20210831_2058.py
  ProjectShop/UserApp/migrations/0003_alter_user_options.py
  ProjectShop/UserApp/migrations/0004_user_is_active.py
  ProjectShop/UserApp/migrations/__init__.py
  ProjectShop/UserApp/models.py
  ProjectShop/UserApp/permissions.py
  ProjectShop/UserApp/urls.py
  ProjectShop/UserApp/views.py
  ProjectShop/order/views.py
  ProjectShop/requirements.txt
  TelegramBot/client.py
Labels: UserModel, REST API

#57 Feature x26 password reset email
  ProjectShop/ProjectShop/settings.py
  ProjectShop/UserApp/templates/UserApp/login.html
  ProjectShop/UserApp/templates/UserApp/password_reset.html
  ProjectShop/UserApp/templates/UserApp/password_reset_complete.html
  ProjectShop/UserApp/templates/UserApp/password_reset_confirm.html
  ProjectShop/UserApp/templates/UserApp/password_reset_done.html
  ProjectShop/UserApp/urls.py
  ProjectShop/UserApp/views.py
Labels: UserModel, User-Authentication, User flow

#102 Added possibility to send data via url via bot_client
  ProjectShop/ProjectShop/settings.py
  TelegramBot/client.py
Labels: telegram-bot

#80 Feature x49 create profile and update page
  ProjectShop/UserApp/forms.py
  ProjectShop/UserApp/templates/UserApp/_base.html
  ProjectShop/UserApp/templates/UserApp/profile.html
  ProjectShop/UserApp/urls.py
  ProjectShop/UserApp/views.py
  ProjectShop/requirements.txt
Labels: UserModel, User-Authentication, User flow

#126 Created token and dispatcher file for running bot with start command
  TelegramBot/TOKEN.py
  TelegramBot/dispatcher.py
Labels: telegram-bot

#108 Feature#98 customize product category, product subcategory, tag, product, review, product media in admin site
  .gitignore
  ProjectShop/ProductApp/admin.py
  ProjectShop/ProductApp/apps.py
  ProjectShop/ProductApp/models.py
  ProjectShop/ProductApp/signals.py
  ProjectShop/ProductApp/utils.py
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/media/default_image/default_image.png
Labels: Admin site, user story

#121 Feature 121. Picture has been added to user profile(update) page.
  ProjectShop/UserApp/forms.py
  ProjectShop/UserApp/templates/UserApp/profile.html
Labels: User flow

#134 hotfix_3 duplicated 'ProductApp' has been removed from settings.py
  ProjectShop/ProjectShop/settings.py
Labels: Hotfix

#129 Feature #128 common router for API root
  ProjectShop/ProjectShop/router.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/order/urls.py
  TelegramBot/TOKEN.py
  TelegramBot/dispatcher.py
Labels: REST API

#119 Feature x118 Swagger and Redoc documentations have been added.
  ProjectShop/ProjectShop/settings.py
  ProjectShop/ProjectShop/urls.py
  ProjectShop/requirements.txt
Labels: documentation, REST API

#141 Feature#107-Create-reply-model
  ProjectShop/ProductApp/models.py
Labels: DataBase-ProductModel

#130 Added buttons to user menu in telegram bot + fixed PEP8
  TelegramBot/client/client.py
  TelegramBot/dispatcher.py
  TelegramBot/handlers/user_menu.py
Labels: telegram-bot
